name: release

on:
  release:
    types: published

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn build
      - uses: kheiakiyama/install-azcopy-action@v1
        with:
          version: 'v10'
      - run: azcopy_v10 copy 'build/*' '${{ secrets.DOCS_STORAGE_LOC }}/core?${{ secrets.DOCS_STORAGE_KEY }}' --recursive